version: "2"

run:
  timeout: 5m

linters:
  enable:  
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    - misspell
    - gosec

issues:
  max-issues-per-linter: 0
  max-same-issues: 0 
