// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/t-yamakoshi/go-mcp-client/pkg/infrastructure"
	"github.com/t-yamakoshi/go-mcp-client/pkg/interfaces"
	"github.com/t-yamakoshi/go-mcp-client/pkg/usecase"
)

// Injectors from wire.go:

func InitializeCLIHandler(configPath string) interfaces.CLIHandler {
	mcpRepositoryImpl := infrastructure.NewMCPRepositoryImpl()
	configRepositoryImpl := infrastructure.NewConfigRepositoryImpl(configPath)
	mcpUseCase := usecase.NewMCPUseCase(mcpRepositoryImpl, configRepositoryImpl)
	configUseCase := usecase.NewConfigUseCase(configRepositoryImpl)
	cliHandler := interfaces.NewCLIHandler(mcpUseCase, configUseCase)
	return cliHandler
}
