// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/t-yamakoshi/go-mcp-client/pkg/infrastructure"
	"github.com/t-yamakoshi/go-mcp-client/pkg/interfaces/cli"
	"github.com/t-yamakoshi/go-mcp-client/pkg/interfaces/message"
	"github.com/t-yamakoshi/go-mcp-client/pkg/usecase"
)

// Injectors from wire.go:

func InitializeCLIHandler(configPath string) *cli.CliHandler {
	configRepositoryImpl := infrastructure.NewConfigRepositoryImpl(configPath)
	mcpRepositoryImpl := infrastructure.NewMCPRepositoryImpl()
	mcpUsecase := usecase.NewMCPUsecase(configRepositoryImpl, mcpRepositoryImpl)
	configUsecase := usecase.NewConfigUsecase(configRepositoryImpl)
	messageHandler := message.NewMessageHandler()
	cliHandler := cli.NewCLIHandler(mcpUsecase, configUsecase, messageHandler)
	return cliHandler
}
