name: Build

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          cache: true

      - name: Install dependencies
        run: go mod download

      - name: Generate Wire code
        run: |
          go install github.com/google/wire/cmd/wire@latest
          cd cmd/mcpclient && wire

      - name: Build
        run: go build -v -o mcp-client ./cmd/mcpclient

      - name: Build for multiple platforms
        run: |
          GOOS=linux GOARCH=amd64 go build -v -o mcp-client-linux-amd64 ./cmd/mcpclient
          GOOS=darwin GOARCH=amd64 go build -v -o mcp-client-darwin-amd64 ./cmd/mcpclient
          GOOS=windows GOARCH=amd64 go build -v -o mcp-client-windows-amd64.exe ./cmd/mcpclient

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mcp-client-binaries
          path: |
            mcp-client
            mcp-client-linux-amd64
            mcp-client-darwin-amd64
            mcp-client-windows-amd64.exe
